import {
  MdHome,
  MdLogin,
  MdLogout,
  MdSettings,
  MdAccountCircle,
  MdAdd,
  MdEdit,
  MdDelete,
  MdSave,
  MdArrowBack,
  MdUploadFile,
  MdDownload,
  MdSearch,
  MdNotifications,
  MdDashboard,
  MdPeople,
  MdChat,
  MdInfo,
  MdWarning,
  MdCheckCircle,
  MdError,
  MdClose,
  MdMenu,
  MdPhone,
  MdPhoneAndroid,
  MdSignalCellularAlt,
  MdLocationOn,
  MdMap,
  MdWork
} from "react-icons/md";

export const CustomIcons = {
  home: MdHome,
  login: MdLogin,
  logout: MdLogout,
  settings: MdSettings,
  account: MdAccountCircle,
  add: MdAdd,
  edit: MdEdit,
  delete: MdDelete,
  save: MdSave,
  back: MdArrowBack,
  upload: MdUploadFile,
  download: MdDownload,
  search: MdSearch,
  notifications: MdNotifications,
  dashboard: MdDashboard,
  users: MdPeople,
  chat: MdChat,
  info: MdInfo,
  warning: MdWarning,
  success: MdCheckCircle,
  error: MdError,
  close: MdClose,
  menu: MdMenu,
  phone: MdPhone,
  mobileScreen: MdPhoneAndroid,
  signal: MdSignalCellularAlt,
  locationDot: MdLocationOn,
  plans: MdWork,
  locationSelect: MdMap
};
