const tokens = {
  loginContainer: 'max-w-screen-sm mx-auto sm:w-1/3 md:w-1/4 lg:w-1/5 xl:w-1/6',
  loginWrapper: 'container mx-auto flex justify-center items-center h-screen',
  loginBox: 'w-full max-w-[28rem]',
  loginCard: 'bg-boxdark shadow-lg rounded-lg px-8 py-10',
  loginLogoWrapper: 'flex justify-center items-center pb-5',
  formGroup: 'mb-4',
  formGroupPassword: 'mb-6',
  label: 'block text-white pb-5 text-center',
  input:
    'w-full px-3 py-2 text-black border rounded-md bg-white focus:outline-none focus:ring-2 focus:ring-white/50 active:ring-2 active:ring-white/50',
  errorText: 'font-bold text-white text-sm',
  primaryButton:
    'w-full bg-white text-boxdark font-bold py-2 px-4 rounded-md border border-transparent hover:bg-boxdark hover:text-white hover:border-white focus:outline-none focus:ring-2 focus:ring-red transition-all duration-300 ease-in-out',
  container: 'relative w-full h-screen',
  backgroundImage: 'object-cover z-0',
  contentWrapper: 'absolute inset-0 z-10 flex flex-col justify-between',
  header: 'w-full p-4 flex justify-between items-center',
  secondaryButton:
    'group flex items-center gap-2 px-4 py-2 border border-transparent bg-white text-boxdark font-semibold rounded-md transition-colors duration-300 ease-in-out hover:bg-boxdark hover:text-white hover:border-white',
  bottomTextWrapper: 'p-8 text-white bg-black/50 w-full',
  bottomText: 'text-xl font-semibold',
  tableContainer: 'p-4 bg-white dark:bg-boxdark rounded-xl shadow-md overflow-hidden',
  headerWrapper: 'flex flex-col sm:flex-row sm:justify-between sm:items-center mb-4 gap-2',
  headerTitle: 'text-lg font-semibold text-black dark:text-white',
  tableWrapper: 'overflow-x-auto max-h-[50vh] overflow-y-auto block',
  table: 'min-w-full table-auto text-sm text-left border-collapse border rounded-md',
  tableHeadRow: 'bg-gray-100 bg-white text-black uppercase text-xs',
  tableHeadCell: 'p-3 whitespace-nowrap',
  tableHeadActionCell: 'p-3 whitespace-nowrap text-center',
  loadingCell: 'text-center p-4',
  errorCell: 'text-center text-red-500 p-4',
  tableRow: 'border-t border-gray-200 bg-white text-black',
  tableCell: 'p-3',
  tableCellCapitalized: 'p-3 capitalize',
  tableCellCenter: 'p-3 text-center',
  actionWrapper: 'flex flex-wrap justify-center gap-3',
  viewAction: 'text-green-500 hover:underline flex items-center gap-1 cursor-pointer',
  deleteAction: 'text-red-500 hover:underline flex items-center gap-1',
  noUsersCell: 'text-center p-4',
  pageWrapper: 'flex flex-col gap-6 p-6',
  pageTitle: 'text-2xl font-bold text-red',
  pageSubtitle: 'text-base text-red',
  gridWrapper: 'grid grid-cols-3 md:grid-cols-3 gap-6',
  gridLeft: 'col-span-1 flex flex-col gap-2',
  gridRight: 'col-span-2 flex flex-col gap-2',
  inputDark: 'w-full px-5 py-3 text-white border border-white rounded-xl bg-transparent font-medium outline-none transition focus:border-primary active:border-primary dark:bg-darkbox',
  formCardWrapper: 'rounded-lg border border-stroke bg-white px-5 pt-6 pb-2.5 shadow-default dark:border-strokedark dark:bg-boxdark sm:px-7.5 xl:pb-1',
  formScrollableBody: 'h-[60vh] overflow-y-auto justify-between',
  formLabel: 'block mb-3 text-black dark:text-white font-medium',
  formTitle: 'mb-6 text-xl font-semibold text-black dark:text-white',
  dangerButton: 'w-full bg-white text-red font-medium py-3 px-5 rounded-xl border border-transparent transition duration-300 hover:bg-red hover:text-white hover:border-white',
};

export default tokens;
